### ISSUE TITLE
Logging in to the inext website

### ISSUE THREAD

**Issue by marekhihi** [CompitHomeAssistant/HomeAssistant#4]
It is not possible to log in using the password and login from: https://inext.compit.pl

Message: Incorrect username or password

**Comment by Przemko92** [comment]
Please test it on the newest version of integration: @rexopl applied some changes on athentication flow. Make sure you are using your email address (not your username etc.) and the correct password.

**Comment by marekhihi** [comment]
![obraz_2024-10-29_214210031](https://github.com/user-attachments/assets/a59f791d-a14d-495d-a4a0-0adbe488dfa2)
I installed the latest version - the problem still exists.

Logging in from a browser on the inext website using the same data (email + password) works without a problem.

**Comment by rexopl** [comment]
I would try to uninstall and install again new version, if not working, please attach logs from HA.

**Comment by marekhihi** [comment]
Thank you, Uninstalled and reinstalled. Problem remains.

_Ten błąd pochodzi z niestandardowej integracji.
Rejestrator: custom_components.compit
Źródło: custom_components/compit/api.py:46
integracja: Compit (dokumentacja, Problemy)
Pierwsze zdarzenie: 29 października 2024 21:34:11 (3 zdarzenia)
Ostatnio zalogowany: 10:01:52
Server returned: 500 Internal Server Error
Server returned: 401 Unauthorized_

**Comment by Przemko92** [comment]
Now the problem also occurs in my environment. I am working with Compit to solve the problem. Api mobile returns 500 - internal server error and for this reason the integration cannot be initiated.

**Comment by marekhihi** [comment]
It looks like it started working - thanks a lot :)! 
I'll test it and share if there are any problems.

**Comment by Rakon23** [comment]
Udało się zalogować. Mam 29encji ze sterownika r490. Nie widzę encji zadania temp CO1 w trybie pracy ręcznej, brak krzywej grzewczej i to w samej  już aplikacji inext(była i jej używałem).W integracji z HA będzie możliwość zmiany stanu np. z eko na stop, albo praca ręczna -program. Chodzi o jakąś zmiane stanu która zatrzyma pracę pompy ciepła?(tego mi brakuje)
